name: Super-Linter

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
      
  jobs:
    run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Cypress run
      uses:cypress-io/github-action@v2
      with:
        build: npm run build
        start: npm start
        run: npm test
  
